TK1/apps/main/urls.py
from django.urls import path
from .views import home, remove_tips, remove_news, news, tips, fetch_news, fetch_covid_status
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('news/', news, name='news'),
    path('tips/', tips, name='tips'),
    path('remove-tips/<int:id>', remove_tips, name='remove_tips'),
    path('remove-news/<int:id>', remove_news, name='remove_news'),
    path('fetch-news', fetch_news, name='fetch_news'),
    path('fetch-covid-status', fetch_covid_status, name='fetch_covid_status')
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

TK1/apps/nadia/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
app_name = 'TK1.apps.nadia'

urlpatterns = [
    path('lokasiTest', views.lokasiTest, name='lokasiTest' ), 
    path('comment', views.comment, name ='comment'),
]

TK1/apps/teofanus/urls.py
from django.urls import path

from .views import login, register, logout_account, profile

app_name = "teofanus"

urlpatterns = [
    path('login/', login, name="login"),
    path('register/', register, name="register"),
    path('logout_account', logout_account, name="logout_account"),
    path('profile', profile, name="profile"),
]

TK1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TK1.apps.main.urls')),
    path('accounts/', include('TK1.apps.teofanus.urls')),
    path('rapid-test/', include('TK1.apps.nadia.urls')),
]

TK1/apps/linus/models.py
from django.db import models

# Create your models here.

TK1/apps/main/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class News(models.Model):
    title = models.CharField(max_length=150)
    link = models.URLField(max_length=256)
    image_headline = models.URLField(max_length=256)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'news'
        verbose_name_plural = 'news'

    def __str__(self) -> str:self.title

class Tips(models.Model):
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=256)
    image = models.ImageField(null=True, blank=True, upload_to="tips_images/")
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'tip'
        verbose_name_plural = 'tips'

    def __str__(self) -> str:self.title

TK1/apps/nadia/models.py
from django.db import models

# Create your models here.
class KotaModel(models.Model):
    nama_kota = models.CharField(max_length=100)
    def __str__(self):
        return self.nama_kota

class TempatModel(models.Model):
    nama_tempat = models.CharField(max_length=100)
    alamat = models.CharField(max_length=300, blank=True, null=True)
    gmaps = models.CharField(max_length=500, blank=True, null=True)
    deskripsi = models.TextField(max_length = 800)
    lokasi = models.ForeignKey(KotaModel, on_delete=models.CASCADE)
    def __str__(self):
        return "{}.{}".format(self.id, self.nama_tempat)

class CommentModel(models.Model):
    title = models.CharField(max_length=50,null=True, blank=True)
    description = models.TextField(null=True,blank=True)
    def __str__(self):
        return self.title

TK1/apps/patrick/models.py
from django.db import models

# Create your models here.

TK1/apps/teofanus/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .provinces import PROVINCE_CHOICES

# Create your models here.

class UserAccount(AbstractUser):

   email = models.EmailField(unique=True, verbose_name="Email")
   covid_result = models.CharField(max_length=20, verbose_name="Covid Result", null=True)
   test_taken = models.DateTimeField(verbose_name="Time and Date of Last COVID Test", null=True)
   province = models.CharField(max_length=20, choices=PROVINCE_CHOICES)
   profile_image = models.ImageField(null=True, blank=True, upload_to="profile_images/")

   REQUIRED_FIELDS = ['email', 'password']

   class Meta:
      verbose_name = 'user'
      verbose_name_plural = 'users'

TK1/apps/main/forms.py
from django.forms import ModelForm
from .models import News, Tips

class NewsForm(ModelForm):
    class Meta:
        model = News
        exclude = ['user']

class TipsForm(ModelForm):
    class Meta:
        model = Tips
        exclude = ['user']

TK1/apps/nadia/forms.py
from django import forms
from .models import CommentModel

class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentModel
        fields = "__all__"

TK1/apps/teofanus/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password1', 'password2', 'province', 'profile_image']

TK1/apps/linus/views.py
from django.shortcuts import render

# Create your views here.

TK1/apps/main/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import News, Tips
from .forms import NewsForm, TipsForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import requests

NEWS = News.objects.all()
TIPS = Tips.objects.all()

def home(request):
    news_form = NewsForm(request.POST or None)
    tips_form = TipsForm(request.POST or None, request.FILES or None)
    response = { 
        'news': News.objects.all(), 
        'tips': Tips.objects.all(), 
        'news_form': news_form,
        'tips_form': tips_form}
    return render(request, 'main/home.html', response)

@login_required
def news(request):
    form = NewsForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            news = form.save(commit = False)
            news.user = request.user
            news.save()
            messages.success(request, "News added successfully!")
        return render(request, 'main/news.html', {'news': News.objects.all()})

    return redirect('main:home')

@login_required
def tips(request):
    form = TipsForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            tips = form.save(commit = False)
            tips.user = request.user
            tips.save()
            messages.success(request, "Tips added successfully!")
            return render(request, 'main/tips.html', {'tips': Tips.objects.all()})
        else:
            messages.error(request, "The uploaded file must be an image!")
            return redirect('main:home')
    return redirect('main:home')

@login_required
def remove_tips(request, id):
    tips = get_object_or_404(Tips, pk=id)
    tips.delete()
    messages.success(request, "Tips has been deleted")
    return redirect('main:home')

@login_required
def remove_news(request, id):
    news = get_object_or_404(News, pk=id)
    news.delete()
    messages.success(request, "News has been deleted")
    return redirect('main:home')

def fetch_news(request):
    url = "https://newsapi.org/v2/top-headlines?country=id&q=covid&apiKey=37086462a7524d0abaf7b8e2aa221bfa"
    response = requests.get(url).json()

    return JsonResponse(response)

def fetch_covid_status(request):
    url = "https://api.kawalcorona.com/indonesia"
    response = requests.get(url).json()[0]

    return JsonResponse(response)

TK1/apps/nadia/views.py
from django.shortcuts import render, redirect,reverse
from django.http import JsonResponse
from TK1.apps.nadia.models import KotaModel
from TK1.apps.nadia.models import TempatModel
from TK1.apps.nadia.models import CommentModel

# Create your views here.

def lokasiTest(request):
    if not request.user.is_authenticated:
            return redirect('teofanus:login')
    tempats = TempatModel.objects.all()
    if request.method == 'POST':
        query = request.POST['lokasi']
        tempats = tempats.filter(alamat__icontains=request.user.province)
        
    context = {
        'tempats': tempats,
    }
    return render(request, "lokasiTest.html", context)

# fungsi halaman comment
def comment(request):
    comments = CommentModel.objects.all()
    response_data = {}
    if request.POST.get('action') == 'post':
        title = request.POST.get('title')
        description = request.POST.get('description')
        response_data['title'] = title
        response_data['description'] = description
        CommentModel.objects.create(
            title = title,
            description = description,
            )
        return JsonResponse(response_data)
        data = JsonResponse(response_data)
    return render(request, 'Comment.html', {'comments':comments}) 

TK1/apps/patrick/views.py
from django.shortcuts import render

# Create your views here.

TK1/apps/teofanus/views.py
from django.http.response import JsonResponse
from django.shortcuts import redirect, render
from .forms import RegisterForm
from django.contrib.auth.forms import  AuthenticationForm
from django.contrib import messages
from django.contrib.auth import authenticate, get_user, logout
from django.contrib.auth import login as auth_login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model

# Create your views here.

def login(request):
    form = AuthenticationForm(request.POST or None)
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username = username, password = password)
        
        if user is not None:
            auth_login(request, user)
            messages.success(request, "You have logged in successfully!")
            return redirect('main:home')
        else:
            messages.error(
                request, "No account can be found, please check your credentials or register first if you have not done so")
            return redirect('teofanus:login')
    response = {'login_form': form}
    return render(request, 'teofanus/login.html', response)

def register(request):
    form = RegisterForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            # messages.success(request, "Account created successfully!")
            return JsonResponse({"total_user": len(get_user_model().objects.all())})
            # return redirect('teofanus:login')
    response = {'register_form': form}
    return render(request, 'teofanus/register.html', response)

@login_required
def logout_account(request):
    logout(request)
    return redirect('main:home')

@login_required
def profile(request):
    return render(request, 'teofanus/profile.html')

TK1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta charset="utf-8">
  {% block meta %}
  <!-- Title Tag -->
  {% endblock meta %}
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- FONT
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link href="//fonts.googleapis.com/css?family=Raleway:400,300,600" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;600&display=swap" rel="stylesheet">

  <!-- CSS
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  {% block css %}
  <!-- Custom CSS -->
  {% endblock css %}
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- <link href="https://unpkg.com/tailwindcss@^1/dist/tailwind.min.css" rel="stylesheet"> -->

  <!-- Favicon
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <link rel="icon" type="image/png" href="{% static 'main/images/logo.svg' %}">

</head>

<body>
  <!-- NavBar
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <nav id="navbar">
    <button onclick="toggleMenu()" class="border border-black">
      <svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/>
      </svg>
    </button>
    <!-- class="block mt-4 md:inline-block md:mt-0" -->
    <div id="mobileMenu">
      <a href="{% url 'main:home' %}">Home</a>
      <a href="">Statistik</a> 
      <a href="{% url 'TK1.apps.nadia:lokasiTest' %}">Rapid Test</a>
      <a href="">Assesment</a>
      <div id="user">
        {% if user.is_authenticated %}
          <p>Hello <a href="{% url 'teofanus:profile' %}">{{ user.username }} ! (Click to see profile)</a></p>
          <b>/</b>
          <a href="{% url 'teofanus:logout_account' %}">Logout</a>
        {% else %}
          <a href="{% url 'teofanus:register' %}">Register</a>
          <b>/</b>
          <a href="{% url 'teofanus:login' %}">Login</a>
        {% endif %}
      </div>
    </div>
  </nav>

  <script>
    let mobileMenu = document.getElementById('mobileMenu');
    function toggleMenu(){
      if (mobileMenu.style.display === "none") {
        mobileMenu.style.display = "flex";
      } else {
        mobileMenu.style.display = "none";
      }
    }
  </script>

  <!-- Primary Page Layout
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <div id="content">
    {% block content %}
    {% endblock content %}
  </div>

  <!-- Footer
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  <footer id="footer">
    <p>Created with 💖 By kelompok B14</p>
  </footer>

<!-- End Document
  –––––––––––––––––––––––––––––––––––––––––––––––––– -->
  {% block script %}{% endblock script %}
</body>
</html>